//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Characters')
export class CharactersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('integer', { nullable: true })
  health: number;

  @Column('integer', { nullable: true })
  strength: number;

  @Column('integer', { nullable: true })
  speed: number;

  @Column('text', { nullable: true })
  special_move: string;

  @Column('text', { nullable: true })
  image: string;

  @Column('text', { nullable: true })
  youtube_channel: string;

  @Column('integer', { nullable: true })
  fame: number;
}
