//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Moves')
export class MovesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('integer', { nullable: true })
  damage: number;

  @Column('text', { nullable: true })
  type: string;

  @Column('text', { nullable: true })
  animation: string;

  @Column('integer', { nullable: true })
  character_id: number;
}
