//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Players')
export class PlayersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  username: string;

  @Column('text', { nullable: true })
  email: string;

  @Column('text', { nullable: true })
  avatar: string;

  @Column('integer', { nullable: true })
  level: number;

  @Column('integer', { nullable: true })
  favorite_character: number;
}
