//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  CharactersList,
  CharactersCreate,
  CharactersEdit,
} from './resources/Characters';
import { MovesList, MovesCreate, MovesEdit } from './resources/Moves';
import { ArenasList, ArenasCreate, ArenasEdit } from './resources/Arenas';
import { MatchesList, MatchesCreate, MatchesEdit } from './resources/Matches';
import { PlayersList, PlayersCreate, PlayersEdit } from './resources/Players';
import CharactersIcon from '@mui/icons-material/Person';
import MovesIcon from '@mui/icons-material/SportsMma';
import ArenasIcon from '@mui/icons-material/SportsMartialArts';
import MatchesIcon from '@mui/icons-material/SportsMartialArts';
import PlayersIcon from '@mui/icons-material/Person';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a0d71de60">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Characters"
          options={{ label: 'Characters' }}
          list={CharactersList}
          create={CharactersCreate}
          edit={CharactersEdit}
          recordRepresentation="name"
          icon={CharactersIcon}
        />
        <Resource
          name="Moves"
          options={{ label: 'Moves' }}
          list={MovesList}
          create={MovesCreate}
          edit={MovesEdit}
          recordRepresentation="name"
          icon={MovesIcon}
        />
        <Resource
          name="Arenas"
          options={{ label: 'Arenas' }}
          list={ArenasList}
          create={ArenasCreate}
          edit={ArenasEdit}
          recordRepresentation="name"
          icon={ArenasIcon}
        />
        <Resource
          name="Matches"
          options={{ label: 'Matches' }}
          list={MatchesList}
          create={MatchesCreate}
          edit={MatchesEdit}
          recordRepresentation="player1_id"
          icon={MatchesIcon}
        />
        <Resource
          name="Players"
          options={{ label: 'Players' }}
          list={PlayersList}
          create={PlayersCreate}
          edit={PlayersEdit}
          recordRepresentation="username"
          icon={PlayersIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
