//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="TEKKEN 3 Pixelina" />
    <CardContent>
      Un juego de peleas estilo Tekken 3 con personajes youtubers y menús
      inspirados en el juego original, usando arte pixelado.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
