//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';
import grOriginal from 'ra-language-greek';

const enResources = {
  resources: {
    Characters: {
      name: 'Characters',
      fields: {
        name: 'Name',
        health: 'Health',
        strength: 'Strength',
        speed: 'Speed',
        special_move: 'Special_move',
        image: 'Image',
        youtube_channel: 'Youtube_channel',
        fame: 'Fame',
        id: 'id',
      },
    },
    Moves: {
      name: 'Moves',
      fields: {
        name: 'Name',
        damage: 'Damage',
        type: 'Type',
        animation: 'Animation',
        character_id: 'Character_id',
        id: 'id',
      },
    },
    Arenas: {
      name: 'Arenas',
      fields: {
        name: 'Name',
        background_image: 'Background_image',
        weather: 'Weather',
        unlock_level: 'Unlock_level',
        id: 'id',
      },
    },
    Matches: {
      name: 'Matches',
      fields: {
        player1_id: 'Player1_id',
        player2_id: 'Player2_id',
        arena_id: 'Arena_id',
        winner_id: 'Winner_id',
        duration: 'Duration',
        date: 'Date',
        id: 'id',
      },
    },
    Players: {
      name: 'Players',
      fields: {
        username: 'Username',
        email: 'Email',
        avatar: 'Avatar',
        level: 'Level',
        favorite_character: 'Favorite_character',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Characters: {
      name: 'Characters (fr)',
      fields: {
        name: 'Name (fr)',
        health: 'Health (fr)',
        strength: 'Strength (fr)',
        speed: 'Speed (fr)',
        special_move: 'Special_move (fr)',
        image: 'Image (fr)',
        youtube_channel: 'Youtube_channel (fr)',
        fame: 'Fame (fr)',
        id: 'id',
      },
    },
    Moves: {
      name: 'Moves (fr)',
      fields: {
        name: 'Name (fr)',
        damage: 'Damage (fr)',
        type: 'Type (fr)',
        animation: 'Animation (fr)',
        character_id: 'Character_id (fr)',
        id: 'id',
      },
    },
    Arenas: {
      name: 'Arenas (fr)',
      fields: {
        name: 'Name (fr)',
        background_image: 'Background_image (fr)',
        weather: 'Weather (fr)',
        unlock_level: 'Unlock_level (fr)',
        id: 'id',
      },
    },
    Matches: {
      name: 'Matches (fr)',
      fields: {
        player1_id: 'Player1_id (fr)',
        player2_id: 'Player2_id (fr)',
        arena_id: 'Arena_id (fr)',
        winner_id: 'Winner_id (fr)',
        duration: 'Duration (fr)',
        date: 'Date (fr)',
        id: 'id',
      },
    },
    Players: {
      name: 'Players (fr)',
      fields: {
        username: 'Username (fr)',
        email: 'Email (fr)',
        avatar: 'Avatar (fr)',
        level: 'Level (fr)',
        favorite_character: 'Favorite_character (fr)',
        id: 'id',
      },
    },
  },
};
const grResources = {
  resources: {
    Characters: {
      name: 'Characters (gr)',
      fields: {
        name: 'Name (gr)',
        health: 'Health (gr)',
        strength: 'Strength (gr)',
        speed: 'Speed (gr)',
        special_move: 'Special_move (gr)',
        image: 'Image (gr)',
        youtube_channel: 'Youtube_channel (gr)',
        fame: 'Fame (gr)',
        id: 'id',
      },
    },
    Moves: {
      name: 'Moves (gr)',
      fields: {
        name: 'Name (gr)',
        damage: 'Damage (gr)',
        type: 'Type (gr)',
        animation: 'Animation (gr)',
        character_id: 'Character_id (gr)',
        id: 'id',
      },
    },
    Arenas: {
      name: 'Arenas (gr)',
      fields: {
        name: 'Name (gr)',
        background_image: 'Background_image (gr)',
        weather: 'Weather (gr)',
        unlock_level: 'Unlock_level (gr)',
        id: 'id',
      },
    },
    Matches: {
      name: 'Matches (gr)',
      fields: {
        player1_id: 'Player1_id (gr)',
        player2_id: 'Player2_id (gr)',
        arena_id: 'Arena_id (gr)',
        winner_id: 'Winner_id (gr)',
        duration: 'Duration (gr)',
        date: 'Date (gr)',
        id: 'id',
      },
    },
    Players: {
      name: 'Players (gr)',
      fields: {
        username: 'Username (gr)',
        email: 'Email (gr)',
        avatar: 'Avatar (gr)',
        level: 'Level (gr)',
        favorite_character: 'Favorite_character (gr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);
const gr = mergeTranslations(grOriginal, grResources);

const translations = { en, fr, gr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
    { locale: 'gr', name: 'Ελληνικά' },
  ],
);
